In [1]:
import cv2

In [18]:
im_g=cv2.imread("smallgray.png",0)

In [19]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [20]:
cv2.imwrite("newsmallgrayb&w.png",im_g)

True

In [38]:
for i in im_g.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [39]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [41]:
import numpy
h_img=numpy.hstack((im_g,im_g))

In [43]:
print(h_img)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [44]:
v_img=numpy.vstack((im_g,im_g))

In [45]:
print(v_img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [57]:
v_lst=numpy.vsplit(v_img,3)

In [58]:
print(v_lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
